[High]
msaa_sample_count = 8
name = 'High'
shadow_enable = true
shadow_light_count = 8
shadow_resolution = 8192

[Low]
msaa_sample_count = 2
name = 'Low'
shadow_enable = true
shadow_light_count = 6
shadow_resolution = 4096

[Medium]
msaa_sample_count = 1
name = 'Medium'
shadow_enable = true
shadow_light_count = 6
shadow_resolution = 512