[windows]
Content_library = false
asset_browser = false
clipboard = false
commands = false
composer = false
create = false
debug_visualizations = true
depth_visualization = true
fly_camera = false
frame_log = false
gradient_editor = false
graph = false
graph_style = false
grid = false
headset = false
hover_tool = false
icon_browser = false
layers = false
log_settings = false
network = false
node_pproperties = false
operation_stack = false
operations = false
paint_tool = false
performance = false
physics = false
pipelines = false
post_processing = false
properties = true
rendergraph = false
selection = false
settings = true
sheet = false
tail_log = false
timeline = false
tool_properties = false
tools_content_library = false
transform = false
viewport_config = false