["erhe.commands"]
input_event_consumed = "info"
command_state_transition = "info"
input_event_filtered = "info"
input = "info"
input_event = "info"
input_events = "info"
input_frame = "info"

["erhe.gl"]
trace = "off"
debug = "warn"

["erhe.geometry"]
triangulate = "info"
subdivide = "info"
weld = "info"
geometry = "info"
geogram = "info"
build_edges = "info"
tangent_gen = "info"
cone = "info"
torus = "info"
sphere = "info"
polygon_texcoords = "info"
interpolate = "info"
operation = "info"
catmull_clark = "info"
attribute_maps = "info"
merge = "info"

[erhe]
dataformat = "warning"
file = "info"
graph = "warning"

["erhe.raytrace"]
device = "info"
buffer = "info"
geometry = "info"
instance = "info"
scene = "info"
embree = "info"
frame = "info"

["erhe.net"]
server = "info"
net = "info"
socket = "info"
client = "info"

["erhe.graphics"]
threads = "info"
fragment_outputs = "info"
program = "info"
save_png = "info"
buffer = "info"
context = "trace"
debug = "info"
framebuffer = "info"
glsl = "info"
load_png = "info"
shader_monitor = "info"
texture = "info"
vertex_stream = "info"
texture_frame = "info"
vertex_attribute = "info"
render_pass = "info"
startup = "info"

["erhe.gltf"]
log = "info"

["erhe.imgui"]
performance = "info"
input_events = "info"
imgui = "info"
windows = "info"
frame = "info"

["erhe.xr"]
log = "info"

["erhe.primitive"]
primitive_builder = "warning"
primitive = "warning"

["erhe.rendergraph"]
frame = "info"
tail = "info"

["erhe.item"]
log = "info"
log_frame = "info"

["erhe.physics"]
physics = "info"
physics_frame = "info"

["erhe.math"]
input_axis = "warning"
input_axis_frame = "warning"

["erhe.renderer"]
draw = "info"
render = "info"
startup = "info"
buffer_writer = "info"
log_gpu_ring_buffer = "info"

["erhe.scene"]
log = "warning"
log_frame = "info"
mesh_raytrace = "info"

["erhe.scene_renderer"]
draw = "info"
render = "info"
log_program_interface = "info"
forward_renderer = "info"
shadow_renderer = "info"
startup = "info"
material_buffer = "info"
primitive_buffer = "info"

["erhe.window"]
space_mouse = "info"
window = "info"
window_event = "info"
renderdoc = "info"

["erhe.ui"]
text_buffer = "info"
font = "info"
